<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$archiver</key>
	<string>NSKeyedArchiver</string>
	<key>$objects</key>
	<array>
		<string>$null</string>
		<string>1830</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>70</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>3</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>31</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>51</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>30</integer>
			</dict>
			<key>EX</key>
			<dict>
				<key>CF$UID</key>
				<integer>6</integer>
			</dict>
			<key>EY</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>4</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>5</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>23</integer>
			</dict>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>12</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>10</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>11</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>0</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>28</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>20</integer>
			</dict>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>1</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<false/>
			<key>plotlines</key>
			<true/>
			<key>plotsymbols</key>
			<false/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<true/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>8</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>26</integer>
			</dict>
			<key>sticksize</key>
			<real>20</real>
			<key>symbol</key>
			<integer>0</integer>
			<key>symbolsize</key>
			<real>10</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		AAAAAAAA8D8AAAAAAAAAQAAAAAAAAAhAAAAAAAAAEEAAAAAAAAAUQAAAAAAA
		ABhAAAAAAAAAHEAAAAAAAAAgQAAAAAAAACJAAAAAAAAAJEAAAAAAAAAmQAAA
		AAAAAChAAAAAAAAAKkAAAAAAAAAsQAAAAAAAAC5AAAAAAAAAMEAAAAAAAAAx
		QAAAAAAAADJAAAAAAAAAM0AAAAAAAAA0QAAAAAAAADVAAAAAAAAANkAAAAAA
		AAA3QAAAAAAAADhAAAAAAAAAOUAAAAAAAAA6QAAAAAAAADtAAAAAAAAAPEAA
		AAAAAAA9QAAAAAAAAD5AAAAAAAAAP0AAAAAAAABAQAAAAAAAgEBAAAAAAAAA
		QUAAAAAAAIBBQAAAAAAAAEJAAAAAAACAQkAAAAAAAABDQAAAAAAAgENAAAAA
		AAAAREAAAAAAAIBEQAAAAAAAAEVAAAAAAACARUAAAAAAAABGQAAAAAAAgEZA
		AAAAAAAAR0AAAAAAAIBHQAAAAAAAAEhAAAAAAACASEAAAAAAAABJQAAAAAAA
		gElAAAAAAAAASkAAAAAAAIBKQAAAAAAAAEtAAAAAAACAS0AAAAAAAABMQAAA
		AAAAgExAAAAAAAAATUAAAAAAAIBNQAAAAAAAAE5AAAAAAACATkAAAAAAAABP
		QAAAAAAAgE9AAAAAAAAAUEAAAAAAAEBQQAAAAAAAgFBAAAAAAADAUEAAAAAA
		AABRQAAAAAAAQFFAAAAAAACAUUAAAAAAAMBRQAAAAAAAAFJAAAAAAABAUkAA
		AAAAAIBSQAAAAAAAwFJAAAAAAAAAU0A=
		</data>
		<data>
		AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAA
		APA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAA
		AAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADw
		PwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAA
		AADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
		AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA
		8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAA
		AAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/
		AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAA
		APA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAA
		AAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADw
		PwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAA
		AADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
		AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8=
		</data>
		<data>
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
		</data>
		<data>
		i8MET1etxz8oKEwaivHEPxQ66lOTbMM/fqX1mLI2wj8aV9RBXJ3BPx/rfHLh
		gsE/usK3CM9EwT+YHPq2IcTBPzQJivQJfsI/UoaNCHL1wz9cdVjg5sTFP4Su
		qnme4sc/XUyR7PmXyj+amZmZmZnJPzMzMzMzM9M/AAAAAAAA4D8AAAAAAAAA
		QAkQvV/oOMY/uQ6xDTI7xD+PgFR1QWnCP3V24Tg9QME/OpfDGGWJwD+F8rHT
		xkLAP35rMvDLWMA/KvlO3EnXwD+BeLw5JfPBPxyAu2xcb8M/wbJNksB5xT/q
		WRLYQBnIP+LoVYMeOcs/mpmZmZmZyT8zMzMzMzPTP5qZmZmZmdk/AAAAAAAA
		8D8S50u0ooHGP4c68wHr0sQ/de90EYgUwz8HypElTTHCP1/qZCautcE/5y+2
		DVXRwT/inotOWyrCP9koSM88B8M/yCVrgapaxD/feTf8+0DGP4/zESTKx8g/
		ERoYX3ttzD8zMzMzMzPTPzMzMzMzM9M/AAAAAAAA4D8AAAAAAAAAQDDwVSBk
		oMY/HGqdc6E1xT92CRb0uSXEPy+wrBqxjsQ/avD2z7k+wz/JscbTLOPDP3LU
		kAnXgsQ/ME1Ty9E/xj84vHsnrKjIP/kAiTncS8w/OZOgXXSk0D8zMzMzMzPT
		P5qZmZmZmdk/zczMzMzM7D+0LcY+d/TEPzQHBM1/WsM/gPa+VobGwj/Ocoa4
		aRnDPxSQ/KruZMQ/PoofipKNxj98avAHiL/JPzG3LpVZnc0/8bz2wOtc0T8z
		MzMzMzPTP5qZmZmZmdk/ZmZmZmZm5j8=
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>/Users/nathanhartland/Dropbox/NHThesis/3-PDFdet/t0/data</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableString</string>
				<string>NSString</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableString</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>Import</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<string>NSColor pasteboard type</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableSet</string>
				<string>NSSet</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableSet</string>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MCAwIDAA
			</data>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColor</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColor</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColorWell</string>
				<string>NSControl</string>
				<string>NSView</string>
				<string>NSResponder</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColorWell</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>22</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>21</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC42NjY2NjY2NjY3AA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>24</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MAA=
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>27</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>29</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>DataBuffer</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>DataBuffer</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>30</integer>
			</dict>
			<key>EX</key>
			<dict>
				<key>CF$UID</key>
				<integer>34</integer>
			</dict>
			<key>EY</key>
			<dict>
				<key>CF$UID</key>
				<integer>35</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>32</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>33</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>45</integer>
			</dict>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>39</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>37</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>38</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>3</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>49</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>43</integer>
			</dict>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>1</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<true/>
			<key>plotlines</key>
			<false/>
			<key>plotsymbols</key>
			<true/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<true/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>36</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>sticksize</key>
			<real>20</real>
			<key>symbol</key>
			<integer>8</integer>
			<key>symbolsize</key>
			<real>5</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		AAAAAAAA8D8AAAAAAAAAQAAAAAAAAAhAAAAAAAAAEEAAAAAAAAAUQAAAAAAA
		ABhAAAAAAAAAHEAAAAAAAAAgQAAAAAAAACJAAAAAAAAAJEAAAAAAAAAmQAAA
		AAAAAChAAAAAAAAAKkAAAAAAAAAsQAAAAAAAAC5AAAAAAAAAMEAAAAAAAAAx
		QAAAAAAAADJAAAAAAAAAM0AAAAAAAAA0QAAAAAAAADVAAAAAAAAANkAAAAAA
		AAA3QAAAAAAAADhAAAAAAAAAOUAAAAAAAAA6QAAAAAAAADtAAAAAAAAAPEAA
		AAAAAAA9QAAAAAAAAD5AAAAAAAAAP0AAAAAAAABAQAAAAAAAgEBAAAAAAAAA
		QUAAAAAAAIBBQAAAAAAAAEJAAAAAAACAQkAAAAAAAABDQAAAAAAAgENAAAAA
		AAAAREAAAAAAAIBEQAAAAAAAAEVAAAAAAACARUAAAAAAAABGQAAAAAAAgEZA
		AAAAAAAAR0AAAAAAAIBHQAAAAAAAAEhAAAAAAACASEAAAAAAAABJQAAAAAAA
		gElAAAAAAAAASkAAAAAAAIBKQAAAAAAAAEtAAAAAAACAS0AAAAAAAABMQAAA
		AAAAgExAAAAAAAAATUAAAAAAAIBNQAAAAAAAAE5AAAAAAACATkAAAAAAAABP
		QAAAAAAAgE9AAAAAAAAAUEAAAAAAAEBQQAAAAAAAgFBAAAAAAADAUEAAAAAA
		AABRQAAAAAAAQFFAAAAAAACAUUAAAAAAAMBRQAAAAAAAAFJAAAAAAABAUkAA
		AAAAAIBSQAAAAAAAwFJAAAAAAAAAU0A=
		</data>
		<data>
		J6CJsOHp8D9seHqlLEPxP83MzMzMzPA/JXUCmggb8T+U9gZfmEzxP1MFo5I6
		AfE/Imx4eqUs8T9B8WPMXUvxP02EDU+vlPE/KqkT0ETY8T8Q6bevA+fxPwK8
		BRIUP/I/w9MrZRni8j89CtejcD3yPxx8YTJVMPY/H/RsVn2u8T9uNIC3QIIA
		QEATYcPTK/E/MlUwKqkT8T+7uI0G8BbxPwMJih9j7vA/eHqlLEMc8T8Cmggb
		nl7xP8NkqmBUUvE/3gIJih9j8T9hMlUwKqnxP+F6FK5H4fE/1lbsL7sn8j8Q
		6bevA+fyP6kT0ETY8PI/HcnlP6Tf8z8mUwWjkjr1PxIUP8bctfc/pb3BFybT
		AkBiodY07zjwPy9uowG8Be8/HhZqTfOO8D8wR4/f2/TvP5yiI7n8h/A/6gQ0
		ETY88D8YJlMFo5LwP3/ZPXlYqPA/wOyePCzU8D+jI7n8h/TwP+AtkKD4MfE/
		x0s3iUFg8T/xY8xdS8jxPwrXo3A9CvM/uECC4seY8z/XNO84RUf+Pw4tsp3v
		p/E/vTrHgOz17z/ZCMTr+gXvP5T2Bl+YTPE/IEHxY8xd8T9z1xLyQc/wP6Aa
		L90kBvE/yAc9m1Wf8T/qlbIMcazxP28Sg8DKofE/xSCwcmiR8j8yVTAqqRPy
		P7raiv1l9/I/iGNd3EYD+D9ZhjjWxW3xP7WmeccpOvE/AJF++zpw8T9cj8L1
		KFzxPwg9m1Wfq/E/0m9fB84Z8j/D9Shcj8LyP2iz6nO1FfM/1XjpJjEI9D8V
		jErqBDT1P9xoAG+BBPg/hetRuB6F+D8=
		</data>
		<data>
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
		</data>
		<data>
		wCZr1EM0xj/T2cngKHnFP/wApDZxcsM/gIKLFTWYwj97gy9MpgrCP2a9GMqJ
		dsE/cJnTZTGxwT9YyjLEsS7CP4zWUdUEUcM/3e9QFOgTxT81e6AVGLLGPwqi
		7gOQ2sg/TBqjdVQ1zT+oGOdvQiHQP7iSHRuBeNk/GCE82jhi4D+KsOHplTIC
		QNieWRKgpsY/eCgK9Ik8xT9Vh9wMN+DDP7eXNEbrqMI/U5EKYwtBwj8/kSdJ
		10zCPzDYDdsWZcI/pSxDHOviwj9cVfZdEfzDP0MEHEKVmsU/KXl1jgHZxz/l
		8h/Sb1/LP1tCPujZrM4/EAaeew+X0j+Vgm4vaYzaP41iuaXVkOg/5j+k374O
		+T9yio7k8h/GP75qZcIv9cM/Z9Xnaiv2wz9hpu1fWWnCP5NX5xiQvcI/HebL
		C7CPwj9GCI82jljDP/1NKETAIcQ/fcucLouJxT+MuWsJ+aDHPyCYo8fvbco/
		EoPAyqFFzj89CtejcD3SP89OBkfJq9k/CAPPvYdL5D990LNZ9bn9PwN4CyQo
		fsg/JEVkWMUbxT+5x9KHLqjDP9cS8kHPZsU/fERMiSR6xT9eaK7TSEvFP9cX
		CW05l8Y/3nahuU4jyT+qDrkZbsDLP77BFyZTBc8/mGn7V1aa0j/ZzvdT46XV
		Py/APjp15ds/hc5r7BLV6T+IgEOoUrPHP8ZQTrSrkMY/IqZEEr2Mxj9fXoB9
		dOrGP4s3Mo/8wcg/O+RmuAGfyz/ejnBa8KLPP8Mq3sg88tE/18BWCRaH1T91
		kxgEVg7bP6+UZYhjXeI/3ze+9syS6T8=
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>/Users/nathanhartland/Dropbox/NHThesis/3-PDFdet/t0/t0data</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>t0 Covariance</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>40</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<string>NSColor pasteboard type</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MSAwIDAA
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>44</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>48</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>50</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>30</integer>
			</dict>
			<key>EX</key>
			<dict>
				<key>CF$UID</key>
				<integer>54</integer>
			</dict>
			<key>EY</key>
			<dict>
				<key>CF$UID</key>
				<integer>55</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>52</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>53</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>64</integer>
			</dict>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>59</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>57</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>58</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>3</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>62</integer>
			</dict>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>1</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<true/>
			<key>plotlines</key>
			<false/>
			<key>plotsymbols</key>
			<true/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<true/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>56</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>66</integer>
			</dict>
			<key>sticksize</key>
			<real>20</real>
			<key>symbol</key>
			<integer>8</integer>
			<key>symbolsize</key>
			<real>5</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		AAAAAAAA8D8AAAAAAAAAQAAAAAAAAAhAAAAAAAAAEEAAAAAAAAAUQAAAAAAA
		ABhAAAAAAAAAHEAAAAAAAAAgQAAAAAAAACJAAAAAAAAAJEAAAAAAAAAmQAAA
		AAAAAChAAAAAAAAAKkAAAAAAAAAsQAAAAAAAAC5AAAAAAAAAMEAAAAAAAAAx
		QAAAAAAAADJAAAAAAAAAM0AAAAAAAAA0QAAAAAAAADVAAAAAAAAANkAAAAAA
		AAA3QAAAAAAAADhAAAAAAAAAOUAAAAAAAAA6QAAAAAAAADtAAAAAAAAAPEAA
		AAAAAAA9QAAAAAAAAD5AAAAAAAAAP0AAAAAAAABAQAAAAAAAgEBAAAAAAAAA
		QUAAAAAAAIBBQAAAAAAAAEJAAAAAAACAQkAAAAAAAABDQAAAAAAAgENAAAAA
		AAAAREAAAAAAAIBEQAAAAAAAAEVAAAAAAACARUAAAAAAAABGQAAAAAAAgEZA
		AAAAAAAAR0AAAAAAAIBHQAAAAAAAAEhAAAAAAACASEAAAAAAAABJQAAAAAAA
		gElAAAAAAAAASkAAAAAAAIBKQAAAAAAAAEtAAAAAAACAS0AAAAAAAABMQAAA
		AAAAgExAAAAAAAAATUAAAAAAAIBNQAAAAAAAAE5AAAAAAACATkAAAAAAAABP
		QAAAAAAAgE9AAAAAAAAAUEAAAAAAAEBQQAAAAAAAgFBAAAAAAADAUEAAAAAA
		AABRQAAAAAAAQFFAAAAAAACAUUAAAAAAAMBRQAAAAAAAAFJAAAAAAABAUkAA
		AAAAAIBSQAAAAAAAwFJAAAAAAAAAU0A=
		</data>
		<data>
		dY4B2evd4z889x4uOe7kPwh3Z+22C+U/ecxAZfz75T+twJDVrZ7mP3b9gt2w
		beY/46WbxCCw5j8rpPyk2qfmPyaN0TqqmuY/8Uv9vKlI5j+BBMWPMXflP698
		lufB3eQ/vHSTGARW5D+brFEP0ejhP17XL9gN2+M//reSHRuB2j9xj6UPXVDq
		P6Ghf4KLFeQ/lNkgk4yc5D8IA8+9h0vlP8/3U+Olm+U/fZHQlnMp5j++h0uO
		O6XmP9fAVgkWh+Y/JzEIrBxa5j8ps0EmGTnmP8gMVMa/z+U/Imx4eqUs5T/C
		o40j1uLkPy140VeQZuM/G9gqweJw4j/jqrLviuDgPxkEVg4tst0/pg9dUN8y
		7z9QcLGiBtPiPzemJyzxgOI/JXoZxXJL5D/h0cYRa/HjP5KumXyzzeQ/QUgW
		MIFb5D/cgM8PI4TkP/fkYaHWNOQ/mZ6wxAPK4z+Y+nlTkQrjP/FG5pE/GOI/
		fJv+7EeK4D/fMqfLYmLdP5M6AU2EDdk/YTdsW5TZzD//PuPCgZC8P7nCu1zE
		d+Q/CfmgZ7Pq4j9gArfu5qniP9TxmIHK+OQ/bOwS1VsD5T9qEyf3OxTkPzZZ
		ox6i0eM/NSTusfSh4z/MC7CPTl3iP1oSoKaWreA/ZVOu8C4X3z+2oWKcvwnZ
		P8YzaOif4NI/Zfz7jAsHxj92/YLdsG3kP2ebG9MTluQ/N45Yi08B5T9rgqj7
		AKTkPxRcrKjBNOQ/zGJi83Ft4z/oMF9egH3iPzgQkgVM4OA/S+oENBE23j9i
		SiTRyyjYP5fK2xFOC84/F2U2yCQjxz8=
		</data>
		<data>
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
		</data>
		<data>
		0PI8uDtrwz/fpj/7kSLCP9TxmIHK+L8/mwMEc/T4vT+pTZzc71C8P4uJzce1
		obo/D+7O2m0Xuj+m7V9ZaVK6PxiyutVz0rs/bcoV3uUivj/UK2UZ4li/P6RT
		Vz7L88A/AaQ2cXK/wz8xsfm4NlTEP/QyiuWWVs8/tMh2vp8a0T9Wfa62Yn/w
		P3FV2XdF8MM/2ubG9IQlwj+h20sao3XAP1wDWyVYHL4/DM11GmmpvD+paoKo
		+wC8P9v5fmq8dLs/h/nyAuyjuz8DPj+MEB69P9ydtdsuNL8/Oul942vPwD9Y
		c4Bgjh7DP1bxRuaRP8Q/w2SqYFRSxz+Qa0PFOH/PP37ja88sCdY/rYbEPZY+
		7z+twJDVrZ7DPw9FgT6RJ8E/QlvOpbiqwD+2SrA4nPm9PxkEVg4tsr0/GFsI
		clDCvD/xLhfxnZi9P2ItPgXAeL4/AB3mywuwvz+OzCN/MPDAP7LXuz/eq8I/
		DTfg88MIxT8fv7fpz37IP8Dsnjws1NA//cHAc+/h1j80ETY8vVLzP3u9++O9
		asU/h6dXyjLEwT+NnIU97fC/P38TChFwCME/soUgByXMwD/KVMGopE7APyRi
		SiTRy8A/OEpenWNAwj8fgNQmTu7DP0inrnyW58U/rthfdk8eyj8mUwWjkjrN
		P7g7a7ddaNI/veMUHcnl4T/cRgN4CyTEP+Z0WUxsPsI/1m670FynwT/27o/3
		qpXBP9Pe4AuTqcI/is3HtaFixD/xun7BbtjGP6GEmbZ/Zck/YwtBDkqYzT9A
		h/nyAuzRPwYN/RNcrNo/bagY529C5T8=
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>/Users/nathanhartland/Dropbox/NHThesis/3-PDFdet/t0/expdata</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>Exp Covariance</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>61</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>60</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MCAxIDAA
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>22</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>63</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>65</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>67</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>61</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>41</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableArray</string>
				<string>NSArray</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableArray</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>70</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>72</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>119</integer>
			</dict>
			<key>NSDelegate</key>
			<dict>
				<key>CF$UID</key>
				<integer>118</integer>
			</dict>
			<key>NSFrame</key>
			<dict>
				<key>CF$UID</key>
				<integer>76</integer>
			</dict>
			<key>NSFrameMatrix</key>
			<dict>
				<key>CF$UID</key>
				<integer>74</integer>
			</dict>
			<key>NSMaxSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>116</integer>
			</dict>
			<key>NSMinize</key>
			<dict>
				<key>CF$UID</key>
				<integer>117</integer>
			</dict>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>73</integer>
			</dict>
			<key>NSSharedData</key>
			<dict>
				<key>CF$UID</key>
				<integer>95</integer>
			</dict>
			<key>NSSuperview</key>
			<dict>
				<key>CF$UID</key>
				<integer>73</integer>
			</dict>
			<key>NSTVFlags</key>
			<integer>5</integer>
			<key>NSTextContainer</key>
			<dict>
				<key>CF$UID</key>
				<integer>78</integer>
			</dict>
			<key>NSWindow</key>
			<dict>
				<key>CF$UID</key>
				<integer>77</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>3328</integer>
			<key>angle</key>
			<real>0.0</real>
			<key>autopos</key>
			<false/>
			<key>autoposangle</key>
			<integer>0</integer>
			<key>autoposloc</key>
			<integer>0</integer>
			<key>autoposoffset</key>
			<real>0.0</real>
			<key>dloc.x</key>
			<real>65.9921875</real>
			<key>dloc.y</key>
			<real>-9.890625</real>
			<key>posmode</key>
			<integer>0</integer>
			<key>tag</key>
			<integer>0</integer>
			<key>tbalign</key>
			<integer>0</integer>
			<key>tloc.x</key>
			<real>531.94921875</real>
			<key>tloc.y</key>
			<real>471.25390625</real>
			<key>x</key>
			<real>0.0</real>
			<key>y</key>
			<real>0.0</real>
		</dict>
		<string>$null</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>75</integer>
			</dict>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSPSMatrix</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSPSMatrix</string>
		</dict>
		<string>{{531.94921875, 454.25390625}, {214.39453125, 17}}</string>
		<string>$null</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>94</integer>
			</dict>
			<key>NSHeight</key>
			<real>1000000</real>
			<key>NSLayoutManager</key>
			<dict>
				<key>CF$UID</key>
				<integer>79</integer>
			</dict>
			<key>NSTCFlags</key>
			<integer>0</integer>
			<key>NSTextView</key>
			<dict>
				<key>CF$UID</key>
				<integer>72</integer>
			</dict>
			<key>NSWidth</key>
			<real>1000000</real>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>93</integer>
			</dict>
			<key>NSDelegate</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSLMFlags</key>
			<integer>38</integer>
			<key>NSTextContainers</key>
			<dict>
				<key>CF$UID</key>
				<integer>92</integer>
			</dict>
			<key>NSTextStorage</key>
			<dict>
				<key>CF$UID</key>
				<integer>80</integer>
			</dict>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSAttributes</key>
			<dict>
				<key>CF$UID</key>
				<integer>82</integer>
			</dict>
			<key>NSDelegate</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSString</key>
			<dict>
				<key>CF$UID</key>
				<integer>81</integer>
			</dict>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>CDF Run-II kT Jet pseudodata fit</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>90</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>83</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>84</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>85</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>87</integer>
				</dict>
			</array>
		</dict>
		<string>NSParagraphStyle</string>
		<string>NSFont</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>86</integer>
			</dict>
			<key>NSTabStops</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableParagraphStyle</string>
				<string>NSParagraphStyle</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableParagraphStyle</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>16</integer>
		</dict>
		<string>Helvetica</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSFont</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSFont</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSDictionary</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSDictionary</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSTextStorage</string>
				<string>NSMutableAttributedString</string>
				<string>NSAttributedString</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSTextStorage</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>70</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>78</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSLayoutManager</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSLayoutManager</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSTextContainer</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSTextContainer</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>115</integer>
			</dict>
			<key>NSBackgroundColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>96</integer>
			</dict>
			<key>NSDefaultParagraphStyle</key>
			<dict>
				<key>CF$UID</key>
				<integer>113</integer>
			</dict>
			<key>NSFlags</key>
			<integer>117575268</integer>
			<key>NSInsertionColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSLinkAttributes</key>
			<dict>
				<key>CF$UID</key>
				<integer>105</integer>
			</dict>
			<key>NSMarkedAttributes</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSPreferredTextFinderStyle</key>
			<integer>0</integer>
			<key>NSSelectedAttributes</key>
			<dict>
				<key>CF$UID</key>
				<integer>97</integer>
			</dict>
			<key>NSTextCheckingTypes</key>
			<integer>0</integer>
			<key>NSTextFinder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MSAxIDEA
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>90</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>98</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>99</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>100</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>103</integer>
				</dict>
			</array>
		</dict>
		<string>NSBackgroundColor</string>
		<string>NSColor</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSCatalogName</key>
			<dict>
				<key>CF$UID</key>
				<integer>101</integer>
			</dict>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>22</integer>
			</dict>
			<key>NSColorName</key>
			<dict>
				<key>CF$UID</key>
				<integer>102</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>6</integer>
		</dict>
		<string>System</string>
		<string>selectedTextBackgroundColor</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSCatalogName</key>
			<dict>
				<key>CF$UID</key>
				<integer>101</integer>
			</dict>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSColorName</key>
			<dict>
				<key>CF$UID</key>
				<integer>104</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>6</integer>
		</dict>
		<string>selectedTextColor</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>90</integer>
			</dict>
			<key>NS.keys</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>99</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>106</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>107</integer>
				</dict>
			</array>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>108</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>109</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>112</integer>
				</dict>
			</array>
		</dict>
		<string>NSCursor</string>
		<string>NSUnderline</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MCAwIDEA
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>111</integer>
			</dict>
			<key>NSCursorType</key>
			<integer>13</integer>
			<key>NSHotSpot</key>
			<dict>
				<key>CF$UID</key>
				<integer>110</integer>
			</dict>
			<key>NSOnMouseEntered</key>
			<true/>
		</dict>
		<string>{8, -8}</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSCursor</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSCursor</string>
		</dict>
		<integer>1</integer>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>114</integer>
			</dict>
			<key>NSTabStops</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSParagraphStyle</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSParagraphStyle</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSTextViewSharedData</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSTextViewSharedData</string>
		</dict>
		<string>{10000, 10000}</string>
		<string>{10, 14}</string>
		<string>$null</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>PlotTextView</string>
				<string>NSTextView</string>
				<string>NSText</string>
				<string>NSView</string>
				<string>NSResponder</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>PlotTextView</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>70</integer>
			</dict>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>122</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>125</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>124</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MQA=
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>125</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>127</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>130</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>125</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>132</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>Datapoint</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>135</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>142</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>144</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC4zMzMzMzMzMzMzAA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>147</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>149</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>151</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>157</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableDictionary</string>
				<string>NSDictionary</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableDictionary</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string>Ratio to pseudodata</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>160</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>167</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>169</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>171</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>173</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>175</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>157</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>183</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>190</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>192</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>194</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>196</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>198</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>157</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>206</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>213</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>215</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>217</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>219</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>221</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>14</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>157</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
	</array>
	<key>$top</key>
	<dict>
		<key>alabel0</key>
		<dict>
			<key>CF$UID</key>
			<integer>156</integer>
		</dict>
		<key>alabel1</key>
		<dict>
			<key>CF$UID</key>
			<integer>180</integer>
		</dict>
		<key>alabel2</key>
		<dict>
			<key>CF$UID</key>
			<integer>203</integer>
		</dict>
		<key>alabel3</key>
		<dict>
			<key>CF$UID</key>
			<integer>226</integer>
		</dict>
		<key>align0</key>
		<integer>2</integer>
		<key>align1</key>
		<integer>4</integer>
		<key>align2</key>
		<integer>6</integer>
		<key>align3</key>
		<integer>8</integer>
		<key>alldraw</key>
		<false/>
		<key>angle0</key>
		<real>0.0</real>
		<key>angle1</key>
		<real>0.0</real>
		<key>angle2</key>
		<real>0.0</real>
		<key>angle3</key>
		<real>0.0</real>
		<key>arrowsize</key>
		<real>10</real>
		<key>arrowtype</key>
		<integer>0</integer>
		<key>axis0</key>
		<true/>
		<key>axis1</key>
		<true/>
		<key>axis2</key>
		<false/>
		<key>axis3</key>
		<false/>
		<key>axismode0</key>
		<integer>0</integer>
		<key>axismode1</key>
		<integer>0</integer>
		<key>axismode2</key>
		<integer>0</integer>
		<key>axismode3</key>
		<integer>0</integer>
		<key>axistext0</key>
		<dict>
			<key>CF$UID</key>
			<integer>133</integer>
		</dict>
		<key>axistext1</key>
		<dict>
			<key>CF$UID</key>
			<integer>158</integer>
		</dict>
		<key>axistext2</key>
		<dict>
			<key>CF$UID</key>
			<integer>181</integer>
		</dict>
		<key>axistext3</key>
		<dict>
			<key>CF$UID</key>
			<integer>204</integer>
		</dict>
		<key>axistextcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>134</integer>
		</dict>
		<key>axistextcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>159</integer>
		</dict>
		<key>axistextcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>182</integer>
		</dict>
		<key>axistextcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>205</integer>
		</dict>
		<key>axistimeformat0</key>
		<dict>
			<key>CF$UID</key>
			<integer>136</integer>
		</dict>
		<key>axistimeformat1</key>
		<dict>
			<key>CF$UID</key>
			<integer>161</integer>
		</dict>
		<key>axistimeformat2</key>
		<dict>
			<key>CF$UID</key>
			<integer>184</integer>
		</dict>
		<key>axistimeformat3</key>
		<dict>
			<key>CF$UID</key>
			<integer>207</integer>
		</dict>
		<key>backgroundcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>123</integer>
		</dict>
		<key>buffer</key>
		<dict>
			<key>CF$UID</key>
			<integer>2</integer>
		</dict>
		<key>dp0</key>
		<integer>2</integer>
		<key>dp1</key>
		<integer>2</integer>
		<key>dp2</key>
		<integer>2</integer>
		<key>dp3</key>
		<integer>2</integer>
		<key>dpauto0</key>
		<true/>
		<key>dpauto1</key>
		<true/>
		<key>dpauto2</key>
		<true/>
		<key>dpauto3</key>
		<true/>
		<key>drawbackground</key>
		<true/>
		<key>drawframe</key>
		<true/>
		<key>drawmargin</key>
		<true/>
		<key>expoff0</key>
		<integer>5</integer>
		<key>expoff1</key>
		<integer>5</integer>
		<key>expoff2</key>
		<integer>5</integer>
		<key>expoff3</key>
		<integer>5</integer>
		<key>fliptext0</key>
		<false/>
		<key>fliptext1</key>
		<false/>
		<key>fliptext2</key>
		<false/>
		<key>fliptext3</key>
		<false/>
		<key>forceframe</key>
		<false/>
		<key>forcerenderhigh</key>
		<false/>
		<key>framearrows</key>
		<false/>
		<key>framecolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>121</integer>
		</dict>
		<key>framestyle</key>
		<integer>0</integer>
		<key>framewidth</key>
		<real>2</real>
		<key>graphic</key>
		<dict>
			<key>CF$UID</key>
			<integer>120</integer>
		</dict>
		<key>grid0</key>
		<false/>
		<key>grid1</key>
		<false/>
		<key>grid2</key>
		<false/>
		<key>grid3</key>
		<false/>
		<key>gridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>143</integer>
		</dict>
		<key>gridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>168</integer>
		</dict>
		<key>gridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>191</integer>
		</dict>
		<key>gridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>214</integer>
		</dict>
		<key>gridfront0</key>
		<true/>
		<key>gridfront1</key>
		<true/>
		<key>gridfront2</key>
		<true/>
		<key>gridfront3</key>
		<true/>
		<key>gridpattern0</key>
		<integer>0</integer>
		<key>gridpattern1</key>
		<integer>0</integer>
		<key>gridpattern2</key>
		<integer>0</integer>
		<key>gridpattern3</key>
		<integer>0</integer>
		<key>gridwidth0</key>
		<real>0.5</real>
		<key>gridwidth1</key>
		<real>0.5</real>
		<key>gridwidth2</key>
		<real>0.5</real>
		<key>gridwidth3</key>
		<real>0.5</real>
		<key>legendbg</key>
		<false/>
		<key>legendbgcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>131</integer>
		</dict>
		<key>legendcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>129</integer>
		</dict>
		<key>legendfont</key>
		<dict>
			<key>CF$UID</key>
			<integer>128</integer>
		</dict>
		<key>legendspace</key>
		<integer>20</integer>
		<key>legendwidth</key>
		<integer>12</integer>
		<key>legendx</key>
		<integer>100</integer>
		<key>legendy</key>
		<integer>470</integer>
		<key>marginbottom</key>
		<real>80</real>
		<key>margincolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>126</integer>
		</dict>
		<key>marginleft</key>
		<real>80</real>
		<key>marginright</key>
		<real>10</real>
		<key>margintop</key>
		<real>10</real>
		<key>mgrid0</key>
		<false/>
		<key>mgrid1</key>
		<false/>
		<key>mgrid2</key>
		<false/>
		<key>mgrid3</key>
		<false/>
		<key>mgridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>148</integer>
		</dict>
		<key>mgridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>172</integer>
		</dict>
		<key>mgridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>195</integer>
		</dict>
		<key>mgridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>218</integer>
		</dict>
		<key>mgridfront0</key>
		<true/>
		<key>mgridfront1</key>
		<true/>
		<key>mgridfront2</key>
		<true/>
		<key>mgridfront3</key>
		<true/>
		<key>mgridpattern0</key>
		<integer>0</integer>
		<key>mgridpattern1</key>
		<integer>0</integer>
		<key>mgridpattern2</key>
		<integer>0</integer>
		<key>mgridpattern3</key>
		<integer>0</integer>
		<key>mgridwidth0</key>
		<real>0.5</real>
		<key>mgridwidth1</key>
		<real>0.5</real>
		<key>mgridwidth2</key>
		<real>0.5</real>
		<key>mgridwidth3</key>
		<real>0.5</real>
		<key>mtickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>146</integer>
		</dict>
		<key>mtickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>170</integer>
		</dict>
		<key>mtickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>193</integer>
		</dict>
		<key>mtickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>216</integer>
		</dict>
		<key>mticklength0</key>
		<real>5</real>
		<key>mticklength1</key>
		<real>5</real>
		<key>mticklength2</key>
		<real>5</real>
		<key>mticklength3</key>
		<real>5</real>
		<key>mticks0</key>
		<true/>
		<key>mticks1</key>
		<true/>
		<key>mticks2</key>
		<true/>
		<key>mticks3</key>
		<true/>
		<key>mticksboth0</key>
		<false/>
		<key>mticksboth1</key>
		<false/>
		<key>mticksboth2</key>
		<false/>
		<key>mticksboth3</key>
		<false/>
		<key>mtickwidth0</key>
		<real>1</real>
		<key>mtickwidth1</key>
		<real>1</real>
		<key>mtickwidth2</key>
		<real>1</real>
		<key>mtickwidth3</key>
		<real>1</real>
		<key>numbers0</key>
		<true/>
		<key>numbers1</key>
		<true/>
		<key>numbers2</key>
		<true/>
		<key>numbers3</key>
		<true/>
		<key>numfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>140</integer>
		</dict>
		<key>numfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>165</integer>
		</dict>
		<key>numfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>188</integer>
		</dict>
		<key>numfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>211</integer>
		</dict>
		<key>numoff0</key>
		<integer>5</integer>
		<key>numoff1</key>
		<integer>5</integer>
		<key>numoff2</key>
		<integer>5</integer>
		<key>numoff3</key>
		<integer>5</integer>
		<key>plotlegend</key>
		<true/>
		<key>plotversion</key>
		<dict>
			<key>CF$UID</key>
			<integer>1</integer>
		</dict>
		<key>reverse0</key>
		<false/>
		<key>reverse1</key>
		<false/>
		<key>reverse2</key>
		<false/>
		<key>reverse3</key>
		<false/>
		<key>scaleexpr0</key>
		<dict>
			<key>CF$UID</key>
			<integer>137</integer>
		</dict>
		<key>scaleexpr1</key>
		<dict>
			<key>CF$UID</key>
			<integer>162</integer>
		</dict>
		<key>scaleexpr2</key>
		<dict>
			<key>CF$UID</key>
			<integer>185</integer>
		</dict>
		<key>scaleexpr3</key>
		<dict>
			<key>CF$UID</key>
			<integer>208</integer>
		</dict>
		<key>scalend0</key>
		<dict>
			<key>CF$UID</key>
			<integer>153</integer>
		</dict>
		<key>scalend1</key>
		<dict>
			<key>CF$UID</key>
			<integer>177</integer>
		</dict>
		<key>scalend2</key>
		<dict>
			<key>CF$UID</key>
			<integer>200</integer>
		</dict>
		<key>scalend3</key>
		<dict>
			<key>CF$UID</key>
			<integer>223</integer>
		</dict>
		<key>scalminticks0</key>
		<dict>
			<key>CF$UID</key>
			<integer>155</integer>
		</dict>
		<key>scalminticks1</key>
		<dict>
			<key>CF$UID</key>
			<integer>179</integer>
		</dict>
		<key>scalminticks2</key>
		<dict>
			<key>CF$UID</key>
			<integer>202</integer>
		</dict>
		<key>scalminticks3</key>
		<dict>
			<key>CF$UID</key>
			<integer>225</integer>
		</dict>
		<key>scalspace0</key>
		<dict>
			<key>CF$UID</key>
			<integer>154</integer>
		</dict>
		<key>scalspace1</key>
		<dict>
			<key>CF$UID</key>
			<integer>178</integer>
		</dict>
		<key>scalspace2</key>
		<dict>
			<key>CF$UID</key>
			<integer>201</integer>
		</dict>
		<key>scalspace3</key>
		<dict>
			<key>CF$UID</key>
			<integer>224</integer>
		</dict>
		<key>scalstart0</key>
		<dict>
			<key>CF$UID</key>
			<integer>152</integer>
		</dict>
		<key>scalstart1</key>
		<dict>
			<key>CF$UID</key>
			<integer>176</integer>
		</dict>
		<key>scalstart2</key>
		<dict>
			<key>CF$UID</key>
			<integer>199</integer>
		</dict>
		<key>scalstart3</key>
		<dict>
			<key>CF$UID</key>
			<integer>222</integer>
		</dict>
		<key>smalllog0</key>
		<false/>
		<key>smalllog1</key>
		<false/>
		<key>smalllog2</key>
		<false/>
		<key>smalllog3</key>
		<false/>
		<key>subviews</key>
		<integer>0</integer>
		<key>text</key>
		<dict>
			<key>CF$UID</key>
			<integer>71</integer>
		</dict>
		<key>text0</key>
		<true/>
		<key>text1</key>
		<true/>
		<key>text2</key>
		<true/>
		<key>text3</key>
		<true/>
		<key>textfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>139</integer>
		</dict>
		<key>textfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>164</integer>
		</dict>
		<key>textfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>187</integer>
		</dict>
		<key>textfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>210</integer>
		</dict>
		<key>textoff0</key>
		<integer>5</integer>
		<key>textoff1</key>
		<integer>5</integer>
		<key>textoff2</key>
		<integer>5</integer>
		<key>textoff3</key>
		<integer>5</integer>
		<key>tickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>141</integer>
		</dict>
		<key>tickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>166</integer>
		</dict>
		<key>tickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>189</integer>
		</dict>
		<key>tickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>212</integer>
		</dict>
		<key>ticklength0</key>
		<real>10</real>
		<key>ticklength1</key>
		<real>10</real>
		<key>ticklength2</key>
		<real>10</real>
		<key>ticklength3</key>
		<real>10</real>
		<key>ticks0</key>
		<true/>
		<key>ticks1</key>
		<true/>
		<key>ticks2</key>
		<true/>
		<key>ticks3</key>
		<true/>
		<key>ticksboth0</key>
		<false/>
		<key>ticksboth1</key>
		<false/>
		<key>ticksboth2</key>
		<false/>
		<key>ticksboth3</key>
		<false/>
		<key>tickstyle0</key>
		<integer>0</integer>
		<key>tickstyle1</key>
		<integer>0</integer>
		<key>tickstyle2</key>
		<integer>0</integer>
		<key>tickstyle3</key>
		<integer>0</integer>
		<key>tickwidth0</key>
		<real>2</real>
		<key>tickwidth1</key>
		<real>2</real>
		<key>tickwidth2</key>
		<real>2</real>
		<key>tickwidth3</key>
		<real>2</real>
		<key>trigger0</key>
		<dict>
			<key>CF$UID</key>
			<integer>138</integer>
		</dict>
		<key>trigger1</key>
		<dict>
			<key>CF$UID</key>
			<integer>163</integer>
		</dict>
		<key>trigger2</key>
		<dict>
			<key>CF$UID</key>
			<integer>186</integer>
		</dict>
		<key>trigger3</key>
		<dict>
			<key>CF$UID</key>
			<integer>209</integer>
		</dict>
		<key>verno</key>
		<integer>31</integer>
		<key>winh</key>
		<integer>500</integer>
		<key>winw</key>
		<integer>800</integer>
		<key>winx</key>
		<integer>263</integer>
		<key>winy</key>
		<integer>188</integer>
		<key>xmax1</key>
		<real>79</real>
		<key>xmax2</key>
		<real>1</real>
		<key>xmin1</key>
		<real>0.0</real>
		<key>xmin2</key>
		<real>0.0</real>
		<key>ymax1</key>
		<real>5</real>
		<key>ymax2</key>
		<real>1</real>
		<key>ymin1</key>
		<real>-1.5</real>
		<key>ymin2</key>
		<real>0.0</real>
		<key>zerocolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>150</integer>
		</dict>
		<key>zerocolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>174</integer>
		</dict>
		<key>zerocolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>197</integer>
		</dict>
		<key>zerocolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>220</integer>
		</dict>
		<key>zeroline0</key>
		<false/>
		<key>zeroline1</key>
		<false/>
		<key>zeroline2</key>
		<false/>
		<key>zeroline3</key>
		<false/>
	</dict>
	<key>$version</key>
	<integer>100000</integer>
</dict>
</plist>
